version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "5441:5441"
    environment:
      - MONGO_URI=mongodb://database:27017/fake_google
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    image: sophiagu/frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: mongo:5.0
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
