import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import './Search.css';

const AI_JOKES = [
  "We promise this course project is not generated by AI --- Wait, How can you tell?",
  // "Why did the neural network go to school? To improve its "grades"!",
  // "I asked my AI to tell me a joke—now it's stuck in an infinite loop of puns.",
  // "What's an AI's favorite music? Neural Rap-ture.",
  // "Why don't robots ever get lost? They always follow the right 'path'!",
  // "I tried teaching my AI to say 'hello' in six languages—it's now a polyglot processor."
];

export default function Search() {
  const [q, setQ] = useState('');
  const [results, setResults] = useState([]);
  const [wm, setWm] = useState('');
  const [showResults, setShowResults] = useState(false);
  const [loading, setLoading] = useState(false);
  const [joke, setJoke] = useState('');
  const [history, setHistory] = useState([]);
  const [showHistory, setShowHistory] = useState(false);
  const [roast, setRoast] = useState('');
  const [showRoast, setShowRoast] = useState(false);
  const jokeInterval = useRef(null);

  // Fetch search history when component mounts
  useEffect(() => {
    fetchSearchHistory();
  }, []);

  // cleanup interval on unmount
  useEffect(() => {
    return () => clearInterval(jokeInterval.current);
  }, []);

  const fetchSearchHistory = async () => {
    try {
      const res = await fetch('/api/search/history');
      const data = await res.json();
      setHistory(data.history);
    } catch (err) {
      console.error('Failed to fetch search history:', err);
    }
  };

  const getRoast = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/roast');
      const data = await res.json();
      setRoast(data.roast);
      setShowRoast(true);
    } catch (err) {
      console.error('Failed to get roast:', err);
    } finally {
      setLoading(false);
    }
  };

  const startJokes = () => {
    // show one immediately
    setJoke(AI_JOKES[Math.floor(Math.random() * AI_JOKES.length)]);
    // rotate every 4 seconds
    jokeInterval.current = setInterval(() => {
      setJoke(AI_JOKES[Math.floor(Math.random() * AI_JOKES.length)]);
    }, 4000);
  };

  const stopJokes = () => {
    clearInterval(jokeInterval.current);
    jokeInterval.current = null;
    setJoke('');
  };

  const doSearch = async () => {
    setLoading(true);
    startJokes();

    try {
      const res = await fetch(`/api/search?q=${encodeURIComponent(q)}`);
      const { results, watermark } = await res.json();
      setResults(results);
      setWm(watermark);
      setShowResults(true);
      // Refresh history after new search
      fetchSearchHistory();
    } catch (err) {
      console.error(err);
      setResults([{ title: 'Error', snippet: 'Could not fetch results.', url: '#' }]);
      setShowResults(true);
    } finally {
      stopJokes();
      setLoading(false);
    }
  };

  return (
    <div className="container">
      {loading ? (
        <div className="loading-area">
          <div className="spinner" />
          <p className="joke">{joke}</p>
        </div>
      ) : (
        <>
          <div className="header">
            <Link to="/" className="back-to-search">
              <span className="logo">
                <span className="red">G</span>
                <span className="yellow">I</span>
                <span className="blue">I</span>
                <span className="green">G</span>
                <span className="red">L</span>
                <span className="blue">E</span>
              </span>
            </Link>
          </div>
          <div className="search-box">
            <input
              value={q}
              onChange={e => {
                setQ(e.target.value);
                setShowHistory(e.target.value.length > 0);
              }}
              onKeyDown={e => e.key === 'Enter' && q.trim() && doSearch()}
              className="search-input"
              placeholder="Search Giigle or type a URL"
            />
            <button
              onClick={() => q.trim() && doSearch()}
              className="search-button"
            >
              Search
            </button>
            <button
              onClick={getRoast}
              className="roast-button"
              title="Get roasted based on your search history!"
            >
              Roast Me
            </button>
          </div>
          {showHistory && history.length > 0 && (
            <div className="search-history">
              <h3>Recent Searches</h3>
              <ul>
                {history.map((item, i) => (
                  <li key={i} onClick={() => {
                    setQ(item.query);
                    setShowHistory(false);
                    doSearch();
                  }}>
                    {item.query}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {showResults && (
            <>
              <div className="watermark">{wm}</div>
              <div className="results">
                {results.map((r, i) => (
                  <div className="result" key={i}>
                    <Link to={`/page?url=${encodeURIComponent(r.url)}`}>
                      {r.title}
                    </Link>
                    <div className="url">{r.url}</div>
                    <p className="snippet">{r.snippet}</p>
                  </div>
                ))}
              </div>
            </>
          )}
          {showRoast && (
            <div className="roast-container">
              <h2>Your Search History Roast</h2>
              <p className="roast-text">{roast}</p>
              <button
                onClick={() => setShowRoast(false)}
                className="close-roast-button"
              >
                Close
              </button>
            </div>
          )}
        </>
      )}
    </div>
  );
}