name: Flask CI

on:
  push:
  pull_request:

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pymongo flask flask-cors openai python-dotenv

      - name: Set environment variables
        run: echo "OPENAI_API_KEY=fake-key-for-testing" >> $GITHUB_ENV

      - name: Run app & frontend tests
        run: |
          pytest --cov=app tests/test_app.py tests/test_frontend.py --cov-config=.coveragerc
