name: CD Pipeline

on:
  push:
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv flask pymongo pytest

      - name: Run Pytest
        run: |
          pytest test_db.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker build -t yourdockerhubusername/backend:latest .
          docker build -t yourdockerhubusername/frontend:latest ./frontend
          docker build -t yourdockerhubusername/database:latest ./database

          docker push yourdockerhubusername/backend:latest
          docker push yourdockerhubusername/frontend:latest
          docker push yourdockerhubusername/database:latest

      - name: Deploy to DigitalOcean via SSH
        if: github.ref == 'refs/heads/main' 
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SERVER_IP }} << 'EOF'
          docker pull yourdockerhubusername/backend:latest
          docker pull yourdockerhubusername/frontend:latest
          docker pull yourdockerhubusername/database:latest
          docker-compose up -d
          EOF
