name: Flask Unit Tests

on:
  push:
  pull_request:

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pymongo flask flask-cors openai python-dotenv

      - name: Run database unit tests
        run: |
          pytest --cov=app tests/test_app.py --cov-config=.coveragerc
