name: Database CI

on:
  push:
  pull_request:

jobs:
  test-db:
    runs-on: ubuntu-latest

    services:
        mongodb:
            image: mongo:5.0
            ports:
                - 27017:27017
            options: >-
                --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'" 
                --health-interval 10s 
                --health-timeout 5s 
                --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pymongo flask openai python-dotenv

      - name: Run database unit tests
        run: |
          pytest --cov=database tests/test_db.py --cov-config=.coveragerc
